### ISSUE TITLE
Please assign a license

### ISSUE THREAD

**Issue by LukeGoodsell** [hubentu/MAC#1]
Hi,

I'm interested in trying out MAC, but as it doesn't have a license declaration, [I'm unable to use it](https://choosealicense.com/no-permission/). Please can you [choose a license](https://choosealicense.com/) under which you would like to distribute MAC so that I (and others) can legally use it.

Many thanks,
Luke

**Comment by hubentu** [comment]
Hi @LukeGoodsell ,

Sorry for the late reply. I only help to host the tool. After contacting the author, he chose the license artistic-2.0. I hope it works for you.

Thanks,
Qiang
